 
language: node_js
node_js: 8

jobs:
  include:
  - os: linux
    language: haskell
    ghc: 
      - "8.8"
    install:
      - |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - os: osx
    if: branch = master

script: npm install && npm test

after_success: npm run coverage

cache: npm

addons:
  apt:
    packages:
    - libsecret-1-dev
  homebrew:
    packages:
    - ghc@8.8
    update: true
